spring:
  profiles:
    active: local
  application:
    name: client

mybatis:
  type-aliases-package: com.cinnabar.client.beans
  mapperPackage: com.cinnabar.client.mapper
  mapper-locations: classpath:mapperXml/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    org.springframework: warn
    com.cinnabar.client.mapper: debug
