#定义服务应用名称
spring:

  # redis
  redis:
    host: localhost
    port: 6379
    password:

  datasource:
    url: jdbc:mysql://localhost:3306/baseinfo
    username: root
    password: mysql
#    提示有默认的drive 注释掉手动配置的
#    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

#定义eureka服务端
eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

swagger:
  title: "cloud web rest API"
  description: "cloud web API"
  version: "v1.0.0"
  groupName: ${spring.application.name}

logback:
  # 配置mapper包路径，控制sql打印必须要设置
  mapperDir: ${mybatis.mapperPackage}
  # 设置是否打印mybatis sql, 默认DEBUG，表示打印；设置为ERROR,则不打印
  sqlLevel: DEBUG
  # 设置root logger level, 默认ERROR，可设置为DEBUG, INFO, ERROR等
  rootLevel: INFO
  # 设置日志文件名称，默认server
  appName: server
  # 日志打印路径, 默认为当前路径下的logs目录
  logDir: logs

test:
  # 配置mapper包路径，控制sql打印必须要设置
  mapperDir: ${mybatis.mapperPackage}
  # 设置是否打印mybatis sql, 默认DEBUG，表示打印；设置为ERROR,则不打印
  sqlLevel: DEBUG
  # 设置root logger level, 默认ERROR，可设置为DEBUG, INFO, ERROR等
  rootLevel: INFO
  # 设置日志文件名称，默认server
  appName: server
  # 日志打印路径, 默认为当前路径下的logs目录
  logDir: logs
